# Generated by Django 4.2.6 on 2023-10-07 16:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boy_name', models.CharField(max_length=30)),
                ('girl_name', models.CharField(max_length=33)),
                ('date', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'name',
            },
        ),
        migrations.CreateModel(
            name='Vevar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vevaname', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=250)),
                ('vevar', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime.today)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.name')),
            ],
            options={
                'db_table': 'vevar',
            },
        ),
    ]
